# Directory
config: ./config/base.yml
data_dir: ./input/train/images
save_dir: ./results
exp_name: exp

# Dataset & Transform
dataset: MaskBaseDataset
augmentation: BaseAugmentation
resize: [
  256,
  192
]
valid_ratio: 0.2
balanced_split: true
sampler: 

# Training
seed: 42
max_epochs: 30
batch_size: 8
valid_batch_size: 64
optimizer: Adam
lr: 1e-4
criterion: focal
lr_decay_step: 20
log_interval: 50

# Model
model: EfficientnetB4